object Form1: TForm1
  Left = 329
  Top = 44
  Width = 810
  Height = 677
  Caption = 'Form1'
  Color = cl3DDkShadow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  Menu = MainMenu1
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Image1: TImage
    Left = 232
    Top = 16
    Width = 337
    Height = 201
    Picture.Data = {
      07544269746D6170761D0000424D761D0000000000003E000000280000003C01
      0000BB0000000100010000000000381D0000232E0000232E0000020000000000
      000000000000FFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE021FFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFC001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFCFCD803FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FCFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FCFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFF9FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8E3F803FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFC07FFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FE3FFE0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFF87FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFC3FFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF87FFFFFFFFC3FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFE3FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      1FFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFE3FFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFF87FFFFFFFFFFC7FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFE1FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFE1
      FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFE1FFFFFFFFFFFF87FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFB87FFFFFFFFFFFFE1FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFF11F
      FFFFFFFFFFFFF9CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFF03FFFFFFFFFFFFFFC0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFC07FFFFFFFFFFFFFFE07FFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFC07FFFFFFFFFFFFFFE03
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFF807F
      FFFFFFFFFFFFFC03FFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFF803FFFFFFFFFFFFFFC01FF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFF87FF001FFFFFFFFFFFFFFE01FF0FFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFF87FE007FFFFFFFFFFFFFFF00
      FF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFF87FC01FF
      FFFFFFFFFFFFFF803F0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFF83FC03FFFFFFFFFFFFFFFFC03E0FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFC1F807FFFFFFFFFFFFFFFFF01E3FFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFE0F81FFFFFFFFFFFFFFFFFF8
      047FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFF8781FFF
      FFFFFFFFFFFFFFFE007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFC107FFFFFFFFFFFFFFFFFFF807FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFE01FFFFFFFFFFFFFFFFFFFFC07FFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFE07FFFFFFFFFFFFFFFFFFFF
      C01FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFE07FFFF
      FFFFFFFFFFFFFFFF8607FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFC03FFFFFFFFFFFFFFFFFFFF0F83FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFF079FFFFFFFFFFFFFFFFFFFF1FC07FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFC078FFFFFFFFFFFFFFFFFFFE
      3FC03FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFF80FC3FFF
      FFFFFFFFFFFFFFFC7FC007FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFE01FE3FFFFFFFF0003DFFFFF8FFE003FFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFF001FF1FFFFFFC00001CFFFFF1FFF003FFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFF003FF0FFFFFF8000000FFFFE3
      FFF001FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFE007FFC3FF
      FFC0000000FFFFC3FFF801FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFC007FFC3FFFE000FFE001FFF8FFFF803FFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFC007FFF1FFF800FFFFE00FFF8FFFFC03FFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFE01FFFF9FFF00FFFFFF003FF1F
      FFFC03FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFE01FFFF87F
      E03FFFFFFF00FC3FFFFE39FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFE03FFFFE1F80FFFFFFFFC078FFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFC73FFFFF1F83FFFFFFFFF819FFFFFFFE3FFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFF8FFFFFFF8F0FFFFFFFFFFE03FF
      FFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFF0FFFFFFFC0
      1FFFFFFFFFFF07FFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFE3FFFFFFFE03FFFFFFFFFFF03FFFFFFFF87FFFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFC7FFFFFFFE07FFFFFFFFFFF03FFFFFFFFE1FFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFC7FFFFFFFE03FFFF0007F9F00FF
      FFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFF0FFFFFFFFC0
      3FFF80001C1E703FFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFF1FFFFFFFF830FFE0000001C783FFFFFFFFC3FFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFC3FFFFFFFF078FF000000081FE1FFFFFFFFE1FFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFF8FFFFFFFFE07E7F001FF8003FF0F
      FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFF81FFFF0FFFFFFFFC07
      E3E079FFF007FF07FFFFFFFF8FF80FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFF81
      FFFE1FFFFFFFF87FF007F9FFFC1FFFC1FFFFFFFFEFF80FFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFE7FFFC1FFFFFFFF0FFFC0FF8FFFC0FFFF0FFFFFFFFFFFCFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFE7FFFC3FFFFFFFE1FFFC0FF87FFE0FFFF0
      7FFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFE7FFFF3FFFFFFF83FF
      FC0FF87FFC03FFFC1FFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFE7
      FFFFFFFFFFFF03FFF80FF87FF801FFFE1FFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFF27FFFFFFFFFFFF07FFF007F87FF1F07FFF0FFFFFFFFFFF8FFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFF87FFFFFFFFFFFC1FFFE1F3F83FE3F07FFF
      87FFFFFFFF998FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFC7FFFFFFFFFFFC3FFF
      E1F9F83FE7F83FFFC3FFFFFFFE180FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFCE7
      FFFFFFFFFFF87FFF83F8F81FC7FE1FFFE1FFFFFFFE7C1FFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFF0E7FFFFFFFFFFF07FFF07FC381F8FFF8FFFF0FFFFFFFC7E3FFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFF3FFFFFFFFFFFFF0FFFE0FFE381F1FFF87FF
      F07FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFE3FFFFFFFFFFFFC1FFFC
      1FFF001E7FFFC3FFFC3FFFFFFCFFF007FFFFFFFFFFFFFFFFFFF0FFFFFFFFE7FF
      FFFFFFFFFF83FFF83FFF803CFFFFE1FFFC1FFFFFFCFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFE7F803FFFFFFFF87FFF07FFFC078FFFFE0FFFE0FFFFFFCFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFE7FFFFFFFFFFFF0FFFE0FFFFE071FFFFF07F
      FF8FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFE7FFFFFFFFFFFE1FFFE1
      FFFFF807FFFFFC3FFF81FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFE7FF
      FFFFFFFFFC3FFFC3FFFFFC0FFFFFFE1FFFE1FFFFFCFFF007FFFFFFFFFFFFFFFF
      FFF0FFFFFFFFE7FFFFFFFFFFF07FFF07FFFFFE1FFFFFFF07FFF0FFFFFCFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFE7F803FFFFFFE0FFFE0FFFFFFF3FFFFFFF87
      FFF07FFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFE7FFFFFFFFFFC1FFFE1F
      FFFFFF3FFFFFFFC3FFF83FFFF8FFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFE7FF
      FFFFFFFF87FFF87FFFFFFF1FFFFFFFF0FFFE1FFFFDFFFFFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFC7FFFFFFFFFF87FFF07FFFFFFF1FFFFFFFF87FFE0FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFEFFFFFFFFFFF0FFFF0FFFFFFFF3FFFFFFFF8
      7FFF03FFFFFFFFF3FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFC1FFFC1FF
      FFFFFF1FFFFFFFFE1FFFC1FFFFFFFFE1FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFF83FFF83FFFFFFFF9FFFFFFFFE1FFFE0FFFFFFFFF1FFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFF07FFF83FFFFFFFF9FFFFFFFFF0FFFF07FFFFFFFF8
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFDFFFFFFFFFF0FFFF07FFFFFFFF9FFFFFFFFF
      C3FFFC3FFFFFFFFC7FFFFFFFFFFFFFFFFFF0FFFFFFFFC7FFFFFFFFF1FFFE1FFF
      FFFFFF9FFFFFFFFFE3FFFE1FFFFFFFFE3FFFFFFFFFFFFFFFFFF0FFFFFFFF0FFF
      FFFFFFE3FFF83FFFFFFFFF8FFFFFFFFFF1FFFF8FFFFFFFFF0FFFFFFFFFFFFFFF
      FFF0FFFFFFFE1FFFFFFFFF87FFF07FFFFFFFFF8FFFFFFFFFF87FFFC7FFFFFFFF
      87FFFFFFFFFFFFFFFFF0FFFFFFFE1FFFFFFFFF07FFE0FFFFFFFFFFCFFFFFFFFF
      FC3FFFC1FFFFFFFFC3FFFFFFFFFFFFFFFFF0FFFFFFFC1FFFFFFFFE1FFFC1FFFF
      FFFFFFC7FFFFFFFFFE1FFFE07FFFFFFFF1FFFFFFFFFFFFFFFFF0FFFFFFF87FFF
      FFFFFC3FFF83FFFFFFFFFFC7FFFFFFFFFF0FFFF03FFFFFFFF0FFFFFFFFFFFFFF
      FFF0FFFFFFF0FFFFFFFFFC7FFF87FFFFFFFFFFC7FFFFFFFFFF8FFFF81FFFFFFF
      FCE7FFFFFFFFFFFFFFF0FFFFFFE1FFFFFFFFF87FFF0FFFFFFFFFFFC7FFFFFFFF
      FFC1FFFC1FFFFFFFFE07FFFFFFFFFFFFFFF0FFFFFFE3FFFFFFFFF0FFFE1FFFFF
      FFFFFFC7FFFFFFFFFFE1FFFE0FFFFFFFFF03FFFFFFFFFFFFFFF0FFFFFFC7FFFF
      FFFFE1FFFC1FFFFFFFFFFFC7FEFFFFFFFFE0FFFF87FFFFFFFF01FFFFFFFFFFFF
      FFF0FFFFFF0FFFFFFFFFC3FFF07FFFFFFFFFFFC1E0007FFFFFF07FFFC3FFFFFF
      FE01FFFFFFFFFFFFFFF0FFFFFE1FFFFFFFFF87FFF0FFFFFFFFFFFFE000087FFF
      FFFC3FFFC1FFFFFFFE00FFFFFFFFFFFFFFF0FFFFFC3FFFFFFFFF07FFF1FFFFFF
      FFFFFFE000007FFFFFFC0FFFE1FFFFFFFF00FFFFFFFFFFFFFFF0FFFFFC3FFFFF
      FFFC1FFFC3FFFFFFFFFFFFF0BFFFFFFFFFFE07FFF07FFFFFFF807FFFFFFFFFFF
      FFF0FFFFFC7FFFFFFFF81FFFC3FFFFFFFFFFFFFFFFFFFFFFFFFF03FFF83FFFFF
      FFC01FFFFFFFFFFFFFF0FFFF70FFFFFFFFF83FFF07FFFFFFFFFFFFFFFFFFFFFF
      FFFF81FFFC1FFFFFFFE01F9FFFFFFFFFFFF0FFFE23FFFFFFFFC0FFFE1FFFFFFF
      FFFFFFFFFFFFFFFFFFFFE0FFFE07FFFFFFF80F9FFFFFFFFFFFF0FFFE07FFFFFF
      FF81FFFC3FFFFFFFFFFFFFFFFFFFFFFFFFFFF87FFF03FFFFFFFC033FFFFFFFFF
      FFF0FFF80FFFFFFFFF03FFF87FFFFFFFFFFFFFFFFFFFFFFFFFFFF83FFF83FFFF
      FFFF003FFFFFFFFFFFF0FFF80FFFFFFFFC0FFFF87FFFFFFFFFFFFFF3FBFFFFFF
      FFFFFC3FFFC1FFFFFFFFC07FFFFFFFFFFFF0FFF00FFFFFFFFC1FFFE0FFFFFFFF
      FFFFFFF1F1FFFFFFFFFFFE0FFFF0FFFFFFFFE0FFFFFFFFFFFFF0FFF007FFFFFF
      FC7FFFE3FFFFFFFFFE7FFFE1E0FFFFFFFFFFFF0FFFF87FFFFFFFF1FFFFFFFFFF
      FFF0FFE003FFFFFFF0FFFFC3FFFFFFFFFC7FFFE444FFFFFFFFFFFFC3FFF83FFF
      FFFFF3FFFFFFFFFFFFF0FFC00FFFFFFFE1FFFF87FFFFFFFFFC7FFFE60C7C01FF
      FFFFFFC1FFFE1FFFFFFFE7FFFFFFFFFFFFF0FF803FFFFFFFC3FFFF0FFFFFFFFF
      FE3FFFC71E3FFFFFFFFFFFE0FFFF0FFFFFFFCFFFFFFF3FFFFFF0FF807FFFFFFF
      83FFFC1FFFFFFFFFFF3FFFC7FF1FFFFFFFFFFFE07FFF07FFFFFF8FFFFFFE3FFF
      FFF0FF00FFFFFFFF07FFFC1FFFFFFFFFFF1FFFC7FF1FFFFFFFFFFFF81FFFC3FF
      FFFE1FFFFFFC7FFFFFF09F03FFFFFFFC0FFFF87FFFFFFFFFFF1FDFCFFF9FFFFF
      FFFFFFFC0FFFE1FFFFFC3FFFFFFCFFFFFFF08F03FFFFFFF81FFFF0FFFFFFFFFF
      FF1F9F8FFF8C01FFFFFFFFFE07FFE0FFFFF87FFFFFE0FFFFFFF0060FFFFFFFF0
      7FFFE0FFFFFFFFFFFF9F8F0FFFDFFFFFFFFFFFFF87FFF03FFFF9FFFFFFC3FFFF
      FFF0803FFFFFFFE0FFFFC3FFFFFFFFFFFF8307FFFFFFFFFFFFFFFFFFE3FFFE0F
      FFE1FFFFFFC7FFFFFFF0E0FFFFFFFFC1FFFF83FFFFFFFFFFFF8003FFFFFFFFFF
      FFFFFFFFE1FFFF0FFFE3FFFFFF8FFFFFFFF0F1FFFFFFFF87FFFF07FFFFFFFFFF
      FFC003FFFFFFFFFFFFFFFFFFF0FFFF87FFC7FFFFFF1FFFFFFFF0F1FFFFFFFF07
      FFFE0FFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFC7FFFC1FFCFFFFFFE3FFFFF
      FFF0F8FFFFFFFE0FFFFC1FFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFC3FFFC1
      FF9FFFFFFE7FFFFFFFF0F87FFFFFFC1FFFF83FFFFFFFFFFFFFCFFFFFFFFFFFFF
      FFFFFFFFFE07FFF0FF3FFFFFFCE00FFFFFF0FC1FFFFFF83FFFE07FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFE03FFF87E3FFFFFF9C003FFFFF0FF0FFFFFF03F
      FF80FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF83FFFC387FFFFFF187C3FF
      FFF0FF83FFFFE0FFFF01FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0FFFE
      01FFFFFFE38FF3FFFFF0FFC3FFFFC3FFFE13FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFF0FFFF03FFFFFFC79FF3FFFFF0FFE1FFFF83FFFE07FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFF07FFF03FFFFFFC78FF3FFFFF0FFF8FFFF0FFF
      FC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF81FFF03FFFFFF1F8FF3FF
      FFF0FFFC7FFE0FFFF87FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFE
      00FFFFE01FC7F1FFFFF0FFFE3FFC1FFFF07FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFE0FFE3C7FFFC03FC3F1FFFFF0FFFF1FFC3FFFE1FFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF03F87E3FFF807FE1F9FFFFF0FFFF8FF87FFF
      83FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC1F0FF1FFF003FF079FF
      FFF0FFFFC7F0FFFF07FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE001
      FF8FFF003FF839FFFFF0FFFFE7E3FFFE0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFE001FFC7FE003FFE09FFFFF0FFFFE0C3FFFC1FFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFE003FFE3FE007FFF01FFFFF0FFFFF803FFF8
      3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFFF3FE03FFFFC03F
      FFF0FFFFFC07FFF03FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0F
      FFF1FC07FFFFF01F8030FFFFFC07FFE0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFE0FFFF8781FFFE00103FFF0FFFFFE07FFC3FFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFC387FFFC00383FFF0FFFFFE07FF87
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFE007FFFC7C3F3
      FFF0FFFFFF83FF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3
      FFFF81FFFFCFF1FFFFF0FFFFFFE1FE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFF1FFFFC3FFFF8FF1FF8030FFFFFFF07C1FFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF07FFF81FFFF8FF9FFFFF0FFFFFFF83C3F
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC3FFF00FFFF9FF9FF
      FFF0FFFFFFFC007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      1FFC3C7FFF87F1FFFFF0FFFFFFFF01FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFF8FFC7E3FFF81E1FFFFF0FFFFFFFF03FFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7F8FE1FFFE003FFFFF0FFFFFFFF83FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC1F9FF1FFFF807FF
      FFF0FFFFFFFFC3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      F1F3FFFFFFFF0FFFFFF0FFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC07FFFFFFFFFFFFFFF0FFFFFFFFE3FFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFFFFFFFFFFFFFFF0FFFFFFFFE7FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FE1FFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC1FFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE003FFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      8071FFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFE00F8FFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE001FFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0
      01FFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFE007FFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF007FFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF007FFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
      0FFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFE00FFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC31FFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8F9FFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0F
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFF81FFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFF03FFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC1FFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF03FF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFF
      FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFF
      FFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF0}
  end
  object d: TLabel
    Left = 280
    Top = 232
    Width = 13
    Height = 20
    Caption = 'l1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label1: TLabel
    Left = 280
    Top = 264
    Width = 13
    Height = 20
    Caption = 'l2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label2: TLabel
    Left = 280
    Top = 296
    Width = 18
    Height = 20
    Caption = 'rw'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label3: TLabel
    Left = 280
    Top = 328
    Width = 8
    Height = 20
    Caption = 'x'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label4: TLabel
    Left = 280
    Top = 360
    Width = 9
    Height = 20
    Caption = 'g'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label5: TLabel
    Left = 280
    Top = 392
    Width = 9
    Height = 20
    Caption = 'a'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label6: TLabel
    Left = 128
    Top = 528
    Width = 167
    Height = 20
    Caption = 'D'#322'ugosc linii oboj'#281'tnej:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label7: TLabel
    Left = 440
    Top = 392
    Width = 98
    Height = 20
    Caption = '[w stopniach]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label8: TLabel
    Left = 440
    Top = 360
    Width = 102
    Height = 20
    Caption = 'grubosc [mm]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label9: TLabel
    Left = 440
    Top = 328
    Width = 112
    Height = 20
    Caption = 'dobierz z tabeli'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label10: TLabel
    Left = 440
    Top = 296
    Width = 118
    Height = 20
    Caption = '[promie'#324' gi'#281'cia]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label11: TLabel
    Left = 728
    Top = 32
    Width = 38
    Height = 13
    Caption = 'Label11'
  end
  object Label12: TLabel
    Left = 136
    Top = 568
    Width = 145
    Height = 20
    Caption = 'K'#261't spr'#281#380'ynowania:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label13: TLabel
    Left = 432
    Top = 568
    Width = 98
    Height = 20
    Caption = '[w stopniach]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label14: TLabel
    Left = 440
    Top = 528
    Width = 38
    Height = 20
    Caption = '[mm]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label15: TLabel
    Left = 440
    Top = 232
    Width = 38
    Height = 20
    Caption = '[mm]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label16: TLabel
    Left = 440
    Top = 264
    Width = 38
    Height = 20
    Caption = '[mm]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label17: TLabel
    Left = 16
    Top = 408
    Width = 21
    Height = 20
    Caption = 'Re'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label18: TLabel
    Left = 24
    Top = 344
    Width = 151
    Height = 20
    Caption = 'Wybierz rodzaj stali:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label19: TLabel
    Left = 176
    Top = 408
    Width = 44
    Height = 20
    Caption = '[MPa]'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label20: TLabel
    Left = 392
    Top = 184
    Width = 6
    Height = 29
    Color = clMenu
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clRed
    Font.Height = -23
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object Label21: TLabel
    Left = 288
    Top = 104
    Width = 6
    Height = 29
    Color = clMenu
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clRed
    Font.Height = -23
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object Label22: TLabel
    Left = 472
    Top = 112
    Width = 6
    Height = 29
    Color = clMenu
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clRed
    Font.Height = -23
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object Label23: TLabel
    Left = 552
    Top = 40
    Width = 6
    Height = 29
    Color = clMenu
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clRed
    Font.Height = -23
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object Label24: TLabel
    Left = 400
    Top = 64
    Width = 6
    Height = 29
    Color = clMenu
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clRed
    Font.Height = -23
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object Edit1: TEdit
    Left = 304
    Top = 232
    Width = 121
    Height = 21
    TabOrder = 0
    Text = '0'
    OnChange = Edit1Change
  end
  object Edit2: TEdit
    Left = 304
    Top = 264
    Width = 121
    Height = 21
    TabOrder = 1
    Text = '0'
    OnChange = Edit2Change
  end
  object Edit3: TEdit
    Left = 304
    Top = 296
    Width = 121
    Height = 21
    TabOrder = 2
    Text = '0'
    OnChange = Edit3Change
  end
  object Edit4: TEdit
    Left = 304
    Top = 328
    Width = 121
    Height = 21
    TabOrder = 3
    Text = '0'
    OnChange = Edit4Change
  end
  object Edit5: TEdit
    Left = 304
    Top = 360
    Width = 121
    Height = 21
    TabOrder = 4
    Text = '0'
    OnChange = Edit5Change
  end
  object Edit6: TEdit
    Left = 304
    Top = 392
    Width = 121
    Height = 21
    TabOrder = 5
    Text = '0'
    OnChange = Edit6Change
  end
  object Memo1: TMemo
    Left = 304
    Top = 528
    Width = 121
    Height = 25
    Lines.Strings = (
      'Memo1')
    TabOrder = 6
  end
  object Button1: TButton
    Left = 264
    Top = 440
    Width = 201
    Height = 57
    Caption = 'Oblicz'
    TabOrder = 7
    OnClick = Button1Click
  end
  object Button2: TButton
    Left = 624
    Top = 536
    Width = 137
    Height = 57
    Caption = 'Zamknij'
    TabOrder = 8
    OnClick = Button2Click
  end
  object Button3: TButton
    Left = 560
    Top = 328
    Width = 49
    Height = 25
    Caption = 'Tabela'
    TabOrder = 9
    OnClick = Button3Click
  end
  object Memo2: TMemo
    Left = 304
    Top = 568
    Width = 121
    Height = 25
    Lines.Strings = (
      'Memo2')
    TabOrder = 10
  end
  object ComboBox1: TComboBox
    Left = 40
    Top = 376
    Width = 129
    Height = 21
    ItemHeight = 13
    TabOrder = 11
    Text = '0'
    OnChange = ComboBox1Change
    Items.Strings = (
      'St0S'
      'St3S'
      'St4S'
      'St5'
      'St6'
      'St7')
  end
  object Edit7: TEdit
    Left = 40
    Top = 408
    Width = 129
    Height = 21
    TabOrder = 12
    Text = '0'
  end
  object RadioGroup1: TRadioGroup
    Left = 608
    Top = 384
    Width = 185
    Height = 105
    Caption = 'RadioGroup1'
    Items.Strings = (
      'kropka'
      'przecinek')
    TabOrder = 13
    Visible = False
  end
  object Timer1: TTimer
    OnTimer = Timer1Timer
    Left = 656
    Top = 80
  end
  object MainMenu1: TMainMenu
    Left = 40
    Top = 192
    object Plik1: TMenuItem
      Caption = 'Plik'
      object Zakocz1: TMenuItem
        Caption = 'Zako'#324'cz'
        OnClick = Zakocz1Click
      end
    end
    object Info1: TMenuItem
      Caption = 'Info'
      object Autor1: TMenuItem
        Caption = 'Autor'
        OnClick = Autor1Click
      end
      object Readme1: TMenuItem
        Caption = 'Read me'
        OnClick = Readme1Click
      end
    end
  end
end
